language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t lukaromih/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true lukaromih/docker-react npm run test